server:
  port: 8084
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sports?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&serverTimezone=UTC
    username: root
    password: poiuyt
    #schema: database/import.sql
    #sql-script-encoding: utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    password: poiuyt
    timeout: 10000
    jedis:
      pool:
        max-idle: 10
        max-wait: 100000
        max-active: 200

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  thymeleaf:
    cache: false

